language: bash
sudo: required
services:
- docker
script:
- |
  TEMPDIR=`mktemp -d` &&\
  git clone --depth 1 --branch "master" "https://github.com/${TRAVIS_REPO_SLUG}.git" "${TEMPDIR}" &&\
  docker build -t knesset-data-people "${TEMPDIR}" &&\
  docker run -d --name knessetdatapeople knesset-data-people serve &&\
  git config user.email "deployment-bot@knesset-data-people" &&\
  git config user.name "knesset-data-people-deployment-bot" &&\
  docker exec knessetdatapeople dpp run ./join-mks &&\
  docker exec knessetdatapeople dpp run ./join-committee-meetings &&\
  docker cp knessetdatapeople:/pipelines/data/ ./ &&\
  if ! git diff --shortstat --exit-code data; then
    git add data &&\
    git commit -m "updated data" &&\
    git push https://${GIT_REPO_TOKEN}'@'github.com/${TRAVIS_REPO_SLUG}.git "${TRAVIS_BRANCH}"
  else
    true
  fi &&\
  docker rm -f knessetdatapeople
