language: bash
sudo: required
services:
- docker
script:
- docker build -t knesset-data-people .
- docker run -d --name knessetdatapeople knesset-data-people serve
- if [ "${TRAVIS_EVENT_TYPE}" == "cron" ] && [ "${GIT_REPO_TOKEN}" != "" ] then
    TEMPDIR=`mktemp -d` &&\
    git config user.email "deployment-bot@knesset-data-people" &&\
    git config user.name "knesset-data-people-deployment-bot" &&\
    git clone --depth 1 --branch "${TRAVIS_BRANCH}" "https://github.com/${TRAVIS_REPO_SLUG}.git" "${TEMPDIR}" &&\
    rm -rf data/members data/committees &&\
    docker cp knessetdatapeople:/pipelines/data/members ./data/members &&\
    docker cp knessetdatapeople:/pipelines/data/committees ./data/committees &&\
    if ! git diff --shortstat --exit-code data/members data/committees; then
      git add data/members data/committees &&\
      git commit -m "updated data" &&\
      git push https://${GIT_REPO_TOKEN}'@'github.com/${TRAVIS_REPO_SLUG}.git "${TRAVIS_BRANCH}"
    else
      true
    fi
  else
    true
  fi
- docker rm -f knessetdatapeople
